# -*- coding: utf-8 -*-
"""stream_lit(image_generation).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ys9KiXXvQOT5lMpQu-E3nuNGxzA9uGuH
"""

import streamlit as st
import zipfile, os, torch
import torch.nn as nn
from torchvision import transforms
from torchvision.utils import save_image
from PIL import Image
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder

st.title("Image Generation Playground")

# Upload ZIP
zip_file = st.file_uploader("Upload Image ZIP", type="zip")

if zip_file:
    os.makedirs("data", exist_ok=True)
    with zipfile.ZipFile(zip_file) as z:
        z.extractall("data")

    transform = transforms.Compose([
        transforms.Resize((64,64)),
        transforms.ToTensor(),
        transforms.Normalize([0.5]*3, [0.5]*3)
    ])

    dataset = ImageFolder("data", transform=transform)
    loader = DataLoader(dataset, batch_size=8, shuffle=True)

    st.success("Images loaded")

    # Autoencoder
    autoencoder = nn.Sequential(
        nn.Flatten(),
        nn.Linear(3*64*64, 256),
        nn.ReLU(),
        nn.Linear(256, 3*64*64),
        nn.Unflatten(1,(3,64,64))
    )

    if st.button("Test Autoencoder"):
        x,_ = next(iter(loader))
        recon = autoencoder(x)
        save_image(recon, "ae.png", normalize=True)
        st.image("ae.png")

    # GAN
    G = nn.Sequential(
        nn.Linear(100,256),
        nn.ReLU(),
        nn.Linear(256,3*64*64),
        nn.Tanh()
    )

    if st.button("Generate GAN Images"):
        z = torch.randn(8,100)
        fake = G(z).view(-1,3,64,64)
        save_image(fake, "gan.png", normalize=True)
        st.image("gan.png")

    # Diffusion (toy)
    def add_noise(x):
        return x + 0.1*torch.randn_like(x)

    diffusion = nn.Sequential(
        nn.Flatten(),
        nn.Linear(3*64*64,256),
        nn.ReLU(),
        nn.Linear(256,3*64*64),
        nn.Unflatten(1,(3,64,64))
    )

    if st.button("Diffusion Output"):
        x,_ = next(iter(loader))
        noisy = add_noise(x)
        out = diffusion(noisy)
        save_image(out, "diff.png", normalize=True)
        st.image("diff.png")